# version: '3.8'
# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#     environment:
#       - "discovery.type=single-node"
#       - "xpack.security.enabled=false"
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#       - "9200:9200"
#     volumes:
#       - elasticsearch-data:/usr/share/elasticsearch/data
#     networks:
#       - elk-network
#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.11.1
#     ports:
#       - "5601:5601"
#     environment:
#       - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
#     networks:
#       - elk-network
#     depends_on:
#       - elasticsearch
#   filebeat:
#     image: docker.elastic.co/beats/filebeat:8.11.1
#     user: root
#     volumes:
#       - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
#       - ../:/logs:ro
#     command: filebeat -e -strict.perms=false
#     networks:
#       - elk-network
#       - default
#     depends_on:
#       - elasticsearch
#     restart: always 
# networks:
#   elk-network:
#     driver: bridge
#   default:
#     external: true
#     name: microservice-network
# volumes:
#   elasticsearch-data: